<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Keuangan</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .info { margin-bottom: 15px; }
        .info p { margin: 5px 0; }
        .section { margin-bottom: 20px; }
        .section h3 { border-bottom: 1px solid #ccc; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 20px; text-align: right; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Keuangan</h1>
        <div class="info">
            <p><strong>Periode:</strong> {{ $period['label'] }}</p>
            <p><strong>Dibuat pada:</strong> {{ $generated_at->format('d/m/Y H:i') }}</p>
            <p><strong>Dibuat oleh:</strong> {{ $generated_by }}</p>
        </div>
    </div>

    <div class="section">
        <h3>Statistik Utama</h3>
        <table>
            <tr>
                <th>Deskripsi</th>
                <th>Jumlah</th>
                <th>Perubahan</th>
            </tr>
            <tr>
                <td>{{ $main_stats['revenue']['label'] }}</td>
                <td>Rp {{ number_format($main_stats['revenue']['amount'], 0, ',', '.') }}</td>
                <td>{{ $main_stats['revenue']['growth_label'] }}</td>
            </tr>
            <tr>
                <td>{{ $main_stats['expenditure']['label'] }}</td>
                <td>Rp {{ number_format($main_stats['expenditure']['amount'], 0, ',', '.') }}</td>
                <td>{{ $main_stats['expenditure']['growth_label'] }}</td>
            </tr>
            <tr>
                <td>{{ $main_stats['net_profit']['label'] }}</td>
                <td>Rp {{ number_format($main_stats['net_profit']['amount'], 0, ',', '.') }}</td>
                <td></td>
            </tr>
            <tr>
                <td>{{ $main_stats['total_capital']['label'] }}</td>
                <td>Rp {{ number_format($main_stats['total_capital']['amount'], 0, ',', '.') }}</td>
                <td></td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h3>Produk Terlaris</h3>
        <table>
            <tr>
                <th>Rank</th>
                <th>Nama Produk</th>
                <th>Kode Produk</th>
                <th>Jumlah Terjual</th>
                <th>Harga Rata-rata</th>
                <th>Total Penjualan</th>
                <th>Persentase</th>
            </tr>
            @foreach($top_products as $product)
            <tr>
                <td>{{ $product['rank'] }}</td>
                <td>{{ $product['product_name'] }}</td>
                <td>{{ $product['product_code'] }}</td>
                <td>{{ number_format($product['total_quantity']) }} {{ $product['unit'] }}</td>
                <td>Rp {{ number_format($product['avg_price'], 0, ',', '.') }}</td>
                <td>Rp {{ number_format($product['total_sales'], 0, ',', '.') }}</td>
                <td>{{ $product['percentage'] }}%</td>
            </tr>
            @endforeach
        </table>
    </div>

    <div class="footer">
        <p>Generated by Your Application</p>
    </div>
</body>
</html>